version: '3'
networks:
  kong-net:
    external: false
    
services:
  kong-database:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "kong"
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE : postgres
      KONG_PG_HOST : kong-database
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    restart: on-failure

  kong-migrations-up:
    image: kong:latest
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE : postgres
      KONG_PG_HOST : kong-database
      KONG_PG_PASSWORD: kong
    networks:
      - kong-net
    restart: on-failure

  kong-1:
    image: kong:latest
    tty: true
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE : postgres
      KONG_PG_HOST : kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG : /dev/stdout
      KONG_ADMIN_ACCESS_LOG : /dev/stdout
      KONG_PROXY_ERROR_LOG : /dev/stderr
      KONG_ADMIN_ERROR_LOG : /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8443:8443"
      - "8442:8442"
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net
    restart: on-failure